// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: meat.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MeatCounter_GetMeatSummary_FullMethodName = "/services.MeatCounter/GetMeatSummary"
)

// MeatCounterClient is the client API for MeatCounter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeatCounterClient interface {
	GetMeatSummary(ctx context.Context, in *MeatRequest, opts ...grpc.CallOption) (*MeatSummary, error)
}

type meatCounterClient struct {
	cc grpc.ClientConnInterface
}

func NewMeatCounterClient(cc grpc.ClientConnInterface) MeatCounterClient {
	return &meatCounterClient{cc}
}

func (c *meatCounterClient) GetMeatSummary(ctx context.Context, in *MeatRequest, opts ...grpc.CallOption) (*MeatSummary, error) {
	out := new(MeatSummary)
	err := c.cc.Invoke(ctx, MeatCounter_GetMeatSummary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeatCounterServer is the server API for MeatCounter service.
// All implementations must embed UnimplementedMeatCounterServer
// for forward compatibility
type MeatCounterServer interface {
	GetMeatSummary(context.Context, *MeatRequest) (*MeatSummary, error)
	mustEmbedUnimplementedMeatCounterServer()
}

// UnimplementedMeatCounterServer must be embedded to have forward compatible implementations.
type UnimplementedMeatCounterServer struct {
}

func (UnimplementedMeatCounterServer) GetMeatSummary(context.Context, *MeatRequest) (*MeatSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeatSummary not implemented")
}
func (UnimplementedMeatCounterServer) mustEmbedUnimplementedMeatCounterServer() {}

// UnsafeMeatCounterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeatCounterServer will
// result in compilation errors.
type UnsafeMeatCounterServer interface {
	mustEmbedUnimplementedMeatCounterServer()
}

func RegisterMeatCounterServer(s grpc.ServiceRegistrar, srv MeatCounterServer) {
	s.RegisterService(&MeatCounter_ServiceDesc, srv)
}

func _MeatCounter_GetMeatSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeatCounterServer).GetMeatSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeatCounter_GetMeatSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeatCounterServer).GetMeatSummary(ctx, req.(*MeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeatCounter_ServiceDesc is the grpc.ServiceDesc for MeatCounter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeatCounter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.MeatCounter",
	HandlerType: (*MeatCounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeatSummary",
			Handler:    _MeatCounter_GetMeatSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meat.proto",
}
